male(Balaji).
male(Veena).
male(y).
male(v).
male(b).
male(z).
male(f).

female(s).
female(u).
female(q).
female(r).
female(e).
female(g).
female(h).

father(Balaji,a).
father(Balaji,u).
father(Balaji,q).
father(Balaji,y).
father(Veena,v).
father(Veena,r).
father(y,b).
father(y,e).
father(v,z).
father(b,f).
father(b,g).
father(f,h).

mother(s,a).
mother(s,u).
mother(s,y).
mother(s,q).
mother(u,v).
mother(u,r).
mother(q,b).
mother(q,e).
mother(r,z).
mother(e,f).
mother(e,g).
mother(g,h).

wife(s,d).
wife(u,a).
wife(q,y).
wife(r,v).
wife(e,b).
wife(g,f).

parent(Balaji,s,a).
parent(Balaji,s,u).
parent(Balaji,s,y).
parent(Balaji,s,q).
parent(Veena,u,v).
parent(Veena,u,r).
parent(y,q,b).
parent(y,q,e).
parent(v,r,z).
parent(b,e,f).
parent(b,e,g).
parent(f,g,h).

sister(X,Y):-parent(Veena,B,X),parent(A,B,Y),female(X),X\==Y.
brother(X,Y):-parent(Veena,B,X),parent(A,B,Y),male(X),X\==Y.
sibilings(X,Y):-parent(Veena,B,X),parent(A,B,Y),X\==Y.
husband(X,Y):-wife(Y,X).
son(X,Y):-father(Y,X);mother(Y,X);male(X).
daughter(X,Y):-father(Y,X);mother(Y,X),female(X).
uncle(X,Y):-brother(Z,X),father(Z,Y).
aunt(X,Y):-husband(Z,X),uncle(Z,Y).
cousin(X,Y):-uncle(Z,X),father(Z,Y).
